# Nama workflow
name: Build and Release OpenWrt IPK

# Pemicu:
# 1. Setiap kali ada push tag dengan format 'v*.*.*'
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        # Target SDK yang dipakai
        target:
          - {
              version: "19.07.9",
              arch: "ramips",
              subarch: "mt76x8",
              pkg_arch: "mipsel_24kc",
            }
          # Tambah target lain kalau perlu:
          # - { version: "22.03.5", arch: "ramips", subarch: "mt7621", pkg_arch: "mipsel_24kc" }

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python 2 (dibutuhkan untuk OpenWrt 19.x SDK)
      - name: Install Python 2.x
        run: |
          sudo apt-get update
          sudo apt-get install -y python2

      # Step 3: Download dan setup OpenWrt SDK
      - name: Download and setup OpenWrt SDK
        run: |
          cd ..
          SDK_VERSION=${{ matrix.target.version }}
          SDK_ARCH=${{ matrix.target.arch }}
          SDK_SUBARCH=${{ matrix.target.subarch }}
          SDK_URL="https://downloads.openwrt.org/releases/${SDK_VERSION}/targets/${SDK_ARCH}/${SDK_SUBARCH}/openwrt-sdk-${SDK_VERSION}-${SDK_ARCH}-${SDK_SUBARCH}_gcc-7.5.0_musl.Linux-x86_64.tar.xz"

          echo "Downloading SDK from ${SDK_URL}"
          wget -q ${SDK_URL} -O openwrt-sdk.tar.xz
          tar -xf openwrt-sdk.tar.xz
          mv openwrt-sdk-* openwrt-sdk

          echo "WORK_DIR=$(pwd)/openwrt-sdk" >> $GITHUB_ENV

      # Step 4: Copy source package ke SDK
      - name: Install package sources into SDK
        run: |
          cp -r $GITHUB_WORKSPACE ${{ env.WORK_DIR }}/package/api_c

      # Step 5: Compile package
      - name: Compile the package
        id: compile
        run: |
          cd ${{ env.WORK_DIR }}
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/api_c/compile V=s

          # Simpan path absolut .ipk
          IPK_PATH=$(find ${{ env.WORK_DIR }}/bin/packages -type f -name "*.ipk" | head -n 1)
          echo "ipk_path=$IPK_PATH" >> $GITHUB_OUTPUT

      # Step 6: Upload artifact kalau bukan release tag
      - name: Upload IPK as artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: api-c-ipk-${{ matrix.target.pkg_arch }}
          path: ${{ steps.compile.outputs.ipk_path }}

      # Step 7: Release ke GitHub kalau push tag
      - name: Create GitHub Release and Upload Asset
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.compile.outputs.ipk_path }}
